AWS_ACCESS_KEY_ID="AKIA3JBK2PZZRNBH3ROU"
AWS_SECRET_ACCESS_KEY="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"
aws_region="us-east-2"


# $Env:AWS_ACCESS_KEY_ID="AKIA3JBK2PZZRNBH3ROU"
# $Env:AWS_SECRET_ACCESS_KEY="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"
# $Env:AWS_DEFAULT_REGION="us-east-2"